name: Docker Compose CI

on:
  push:
    branches:
      - lab1
  pull_request:
    branches:
      - lab1

jobs:
  check-rabbitmq:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: "rabbitmq:management"
        ports:
          - "5672:5672"
          - "15672:15672"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and start Docker containers with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for RabbitMQ to be ready
        run: |
          echo "Waiting for RabbitMQ AMQP port to be available..."
          until nc -z -v -w30 rabbitmq 5672; do
            echo "Waiting for RabbitMQ..."
            sleep 5
          done
          echo "RabbitMQ is ready!"

      - name: Test RabbitMQ connection via management API
        run: |
          echo "Testing RabbitMQ management API connection..."
          curl -s --fail http://rabbitmq:15672/api/overview --user guest:guest
          echo "RabbitMQ management API connection successful!"
